In [1]:
#기본 파이썬 라이브러리
import pandas as pd
import numpy as np

c:\Users\dddhs\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\dddhs\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [4]:
data_tech=pd.read_csv(r'C:\Users\dddhs\TS_RL_proj\data\processed\data_tech_features.csv')

data_GARCH=pd.read_csv(r'C:\Users\dddhs\TS_RL_proj\data\processed\GARCH_GJR-GARCH_VaR_0.05_Risk_label.csv')

In [7]:
data_tech.head(20)

,Date,Shanghai Comp,KODEX 200,TOPIX,Brent Crude Oil,Gold Spot,KRW/JPY,KRW/USD,KOSDAQ,KOSPI 200,KRW/CNY,KOSPI 200_MA5,KOSPI 200_MA15,KOSPI 200_EMA5,KOSPI 200_EMA15,KOSPI 200_RSI14,KOSPI 200_BB_MID20,KOSPI 200_BB_UPPER20,KOSPI 200_BB_LOWER20
0,2009-04-17,2503.935059,12910.509766,679.428528,51.959999,867.400024,13.371,1325.800049,483.799988,171.330002,194.324755,171.598001,166.383999,170.855038,166.505376,63.873746,166.383999,177.305127,155.462870
1,2009-04-20,2557.456055,12992.271484,680.204834,51.959999,887.000000,13.536,1327.500000,491.940002,172.300003,194.562510,171.720001,167.093332,171.336693,167.229705,76.439644,167.093332,178.081434,156.105230
2,2009-04-21,2535.827881,12992.271484,663.898682,51.959999,882.099976,13.727,1354.300049,497.190002,171.960007,198.668030,171.706003,168.141999,171.544464,167.820992,74.958299,168.141999,177.579936,158.704063
3,2009-04-22,2461.345947,13166.940430,664.675171,51.959999,891.799988,13.726,1346.599976,509.899994,174.399994,197.463154,172.344000,169.301333,172.496308,168.643368,74.084326,169.301333,176.988826,161.613840
4,2009-04-23,2463.954102,13300.724609,669.333923,51.959999,905.900024,13.618,1333.599976,514.090027,176.139999,195.562586,173.226001,170.346665,173.710872,169.580447,69.951956,170.346665,177.087774,163.605556
5,2009-04-24,2448.594971,13148.357422,666.228149,51.959999,913.599976,13.775,1340.300049,507.500000,174.130005,196.614310,173.786002,170.876666,173.850583,170.149141,63.479290,170.876666,177.462103,164.291230
6,2009-04-27,2405.347900,13003.415039,663.898682,51.959999,907.400024,13.989,1350.500000,505.970001,172.130005,198.130930,173.752002,171.211333,173.277057,170.396749,56.615179,171.211333,177.478959,164.943707
7,2009-04-28,2401.437988,12654.084961,651.474792,51.959999,892.799988,13.927,1344.900024,479.369995,167.240005,197.268844,172.808002,171.119334,171.264706,170.002156,48.233796,171.119334,177.587286,164.651382
8,2009-04-29,2468.191895,13030.134766,651.474792,51.959999,899.799988,13.752,1341.300049,494.470001,172.080002,196.815853,172.344003,171.368668,171.536471,170.261887,65.501354,171.368668,177.663474,165.073861
9,2009-04-30,2477.569092,13312.172852,672.440002,51.959999,890.700012,12.949,1278.099976,500.980011,176.000000,187.693654,172.316003,172.256668,173.024314,170.979151,61.880493,172.256668,176.817810,167.695526
10,2009-05-04,2559.910889,13552.844727,672.440002,54.580002,901.599976,12.770,1262.099976,507.010010,179.690002,185.208013,173.428003,172.937335,175.246210,172.068008,63.831281,172.937335,178.629661,167.245009
11,2009-05-06,2592.520020,13526.518555,672.440002,56.150002,910.500000,12.921,1271.800049,510.019989,178.820007,186.746556,174.766003,173.412669,176.437476,172.912008,61.528047,173.412669,179.806189,167.019148
12,2009-05-07,2597.447021,13582.928711,706.605530,56.470001,915.000000,12.700,1259.099976,513.950012,179.740005,184.841008,177.266003,173.926669,177.538319,173.765507,64.433183,173.926669,181.042654,166.810685
13,2009-05-08,2625.645020,13688.225586,712.817444,58.139999,914.400024,12.477,1228.800049,517.830017,181.039993,180.414047,179.058002,174.582002,178.705544,174.674818,65.347859,174.582002,182.401529,166.762474
14,2009-05-11,2579.747070,13703.261719,719.029480,57.480000,913.000000,12.670,1235.599976,523.909973,181.350006,181.396432,180.128003,175.223336,179.587031,175.509217,66.567481,175.223336,183.598637,166.848035
15,2009-05-12,2618.172119,13582.928711,708.934937,57.939999,923.500000,12.820,1236.699951,526.179993,179.729996,181.533938,180.136002,175.783335,179.634686,176.036814,62.026540,175.783335,184.166274,167.400397
16,2009-05-13,2663.766113,13688.225586,710.487976,57.340000,925.500000,13.018,1241.099976,535.950012,181.139999,182.201213,180.600000,176.372668,180.136457,176.674712,64.361695,176.372668,184.946854,167.798482
17,2009-05-15,2645.262939,13440.031250,703.499512,55.980000,930.900024,13.192,1255.000000,543.539978,177.800003,184.160708,180.212000,176.762002,179.357639,176.815373,55.173477,176.762002,185.001286,168.522717
18,2009-05-18,2652.779053,13387.383789,687.193176,58.470001,921.299988,13.031,1256.000000,545.010010,177.259995,184.258779,179.456000,176.952668,178.658424,176.870951,51.768786,176.952668,185.089427,168.815910
19,2009-05-19,2676.681885,13801.040039,703.499512,58.919998,926.299988,12.923,1242.300049,553.770020,182.759995,182.286395,179.737997,177.394001,180.025614,177.607082,62.275942,177.394001,186.043806,168.744197

In [6]:
data_GARCH.head(20)

,Date,Actual_Return (%),GARCH_Vol,GJR_GARCH_Vol,VaR_95,Risk_Label
0,2009-04-20,0.564563,1.474962,1.469190,-2.749950,lowrisk
1,2009-04-21,-0.197523,1.423665,1.416096,-2.649217,lowrisk
2,2009-04-22,1.408955,1.369916,1.357370,-2.537800,lowrisk
3,2009-04-23,0.992765,1.366743,1.300283,-2.429493,lowrisk
4,2009-04-24,-1.147696,1.338269,1.294011,-2.417593,lowrisk
5,2009-04-27,-1.155214,1.327041,1.304459,-2.437416,lowrisk
6,2009-04-28,-2.882009,1.317202,1.315516,-2.458393,highrisk
7,2009-04-29,2.852956,1.492876,1.647842,-3.088895,lowrisk
8,2009-04-30,2.252450,1.619686,1.493315,-2.795720,lowrisk
9,2009-05-04,2.074916,1.663332,1.651886,-3.096568,lowrisk
10,2009-05-06,-0.485340,1.686212,1.523064,-2.852162,lowrisk
11,2009-05-07,0.513164,1.624381,1.596359,-2.991220,lowrisk
12,2009-05-08,0.720657,1.563988,1.429556,-2.674755,lowrisk
13,2009-05-11,0.171094,1.512337,1.445373,-2.704762,lowrisk
14,2009-05-12,-0.897320,1.452877,1.337823,-2.500714,lowrisk
15,2009-05-13,0.781451,1.419216,1.360154,-2.543082,lowrisk
16,2009-05-15,-1.861087,1.378025,1.267570,-2.367427,highrisk
17,2009-05-18,-0.304179,1.421386,1.437029,-2.688932,lowrisk
18,2009-05-19,3.055624,1.369467,1.312605,-2.452870,lowrisk
19,2009-05-20,0.567444,1.544633,1.307580,-2.443336,lowrisk