### train / validation / test - threshold 기준이 정해져야 tech feature와 GARCH feature 병합가능함 아직 미완

In [1]:
#기본 파이썬 라이브러리
import pandas as pd
import numpy as np

c:\Users\dddhs\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
c:\Users\dddhs\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
data_tech=pd.read_csv(r'C:\Users\dddhs\TS_RL_proj\data\processed\data_tech_features.csv')

data_GARCH=pd.read_csv(r'C:\Users\dddhs\TS_RL_proj\data\processed\data_GARCH_GJR-GARCH_VaR_Risk_Label(전체threshold).csv')

In [5]:
data_tech.head()

,Date,Shanghai Comp,KODEX 200,TOPIX,Brent Crude Oil,Gold Spot,KRW/JPY,KRW/USD,KOSDAQ,KOSPI 200,KRW/CNY,KOSPI 200_MA5,KOSPI 200_MA15,KOSPI 200_EMA5,KOSPI 200_EMA15,KOSPI 200_RSI14,KOSPI 200_BB_MID20,KOSPI 200_BB_UPPER20,KOSPI 200_BB_LOWER20
0,2009-04-17,2503.935059,12910.513672,679.428406,51.959999,867.400024,13.371,1325.800049,483.799988,171.330002,194.324755,171.598001,166.383999,170.855038,166.505376,63.873746,166.383999,177.305127,155.462870
1,2009-04-20,2557.456055,12992.271484,680.204895,51.959999,887.000000,13.536,1327.500000,491.940002,172.300003,194.562510,171.720001,167.093332,171.336693,167.229705,76.439644,167.093332,178.081434,156.105230
2,2009-04-21,2535.827881,12992.271484,663.898621,51.959999,882.099976,13.727,1354.300049,497.190002,171.960007,198.668030,171.706003,168.141999,171.544464,167.820992,74.958299,168.141999,177.579936,158.704063
3,2009-04-22,2461.345947,13166.939453,664.675110,51.959999,891.799988,13.726,1346.599976,509.899994,174.399994,197.463154,172.344000,169.301333,172.496308,168.643368,74.084326,169.301333,176.988826,161.613840
4,2009-04-23,2463.954102,13300.723633,669.334106,51.959999,905.900024,13.618,1333.599976,514.090027,176.139999,195.562586,173.226001,170.346665,173.710872,169.580447,69.951956,170.346665,177.087774,163.605556

In [4]:
data_GARCH.head()

,Date,Actual_Return (%),GARCH_Vol,GJR_GARCH_Vol,VaR_95,Risk_Label
0,2009-04-17,-0.233192,1.432045,1.426891,-2.246073,lowrisk
1,2009-04-20,0.564563,1.378327,1.379095,-2.169582,lowrisk
2,2009-04-21,-0.197523,1.332280,1.312454,-2.062932,lowrisk
3,2009-04-22,1.408955,1.283201,1.273734,-2.000966,lowrisk
4,2009-04-23,0.992765,1.287644,1.210839,-1.900311,lowrisk